### ISSUE TITLE
Unable to download data

### ISSUE THREAD

**Issue by SujithChristopher** [herohuyongtao/deeptag-pytorch#10]
Dear authors of this study,

First i would like to thank you for making your data available online, I would like to access your data, 

But since its posted in baidu drive, its not accessible outside China, can you please tell me other means to download your data. 

thanks in advance.

**Comment by SujithChristopher** [comment]
Thanks, @herohuyongtao for providing the dataset.

**Comment by herohuyongtao** [comment]
For anyone who faces the same issue, the dataset is also available via TeraBox now. Please see [here](https://herohuyongtao.github.io/research/publications/deep-tag/#dataset) for details.
