### ISSUE TITLE
script for training?

### ISSUE THREAD

**Issue by twpark97** [herohuyongtao/deeptag-pytorch#6]
Hello,

I'm doing research for drone autolanding. I would like to utilize deeptag framework, since it's framework fits me well.
To briefly introduce my interest, in order to detect below image, I want to retrain deeptag network with modifying train/label dataset.
![image](https://user-images.githubusercontent.com/20321265/149329219-713b2884-ff46-4971-9728-1b5560ad72e1.png)

But I couldn't find it myself. Can you provide a code for training? 
If I were rude of asking it, sorry in advance.

Thanks,

**Comment by sskzzm** [comment]
I'm not sure how the ID is represented in your marker. If it is an extension of binary NxN marker, you may not need to re-train DeepTag models. Instead, please re-define the codebook and Hamming distance. There are codebooks for AprilTag, ArUco, ARToolkitPlus for your reference. Besides Hamming distance, you may also need to change to code to ignore the detected keypoints in the center part of marker which belongs to the child marker.

**Comment by twpark97** [comment]
thanks for your advice. I'll try all of yours!
